config/routes.rb
Rails3DeviseRspecCucumber::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  resources :users, :only => [:show, :index] do
    resources :microposts, :only => [:create, :destroy, :new]
    resources :albums, :only => [:create, :destroy, :index, :show] do
      resources :photos, :only => [:create, :destroy]
    end
  end

  resources :photos, :only => [:create, :destroy]

  resources :microposts, :only => [:create, :destroy, :new]

  resources :friendships

  resources :albums, :only => [:create, :destroy, :index, :show] do
    resources :photos, :only => [:create, :destroy]
  end

  resources :videos, :only => [:create, :destroy, :index, :show]

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'

  match "/users/:id/friends" => "users#friends", :as => :user_friends
  match "/users/:id" => "users#show", :as => :user_profile

  match "/friends" => "users#friends", :as => :current_user_friends

  match "/news" => "users#news", :as => :news

  match '/home', :to => 'home#index'
  match '/', :to => 'home#index'
  match '/users', :to => 'users#index'

  match "/users/:user_id/albums" => "albums#index", :as => :user_albums

  match "/change_status" => "users#change_status", :as => :user_change_status

  match "/update_status" => "users#update_status", :as => :user_update_status


  match "friendships/:action/:id", :controller => 'friendships', :action => /[a-z_]+/i
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  failed_attempts        :integer         default(0)
#  unlock_token           :string(255)
#  locked_at              :datetime
#  authentication_token   :string(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#  name                   :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :confirmable, :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :confirmed_at, :user_status

  has_many :microposts, :dependent => :destroy

  has_many :albums


  has_many :friendships

  has_many :friends,
           :through => :friendships,
           :conditions => "status = 'accepted'",
           :order => :name


  has_many :requested_friends,
           :through => :friendships,
           :source => :friend,
           :conditions => "status = 'requested'",
           :order => :created_at


  has_many :pending_friends,
           :through => :friendships,
           :source => :friend,
           :conditions => "status = 'pending'",
           :order => :created_at


  def feed
    Micropost.where("user_id = ?", id)
  end

  def news_feed
    Micropost.where("creator_id = ?", id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = current_user unless @user = User.find(params[:id])
    @title = @user.name
    @friends_title = "Friends"
    @micropost = Micropost.new
    @feed_items = @user.feed.paginate(:page => params[:page])
  end

  def friends
    @user = current_user unless @user = User.find_by_id(params[:id])
    @title = @user.name.to_s + "'s Friends"

    @friends =  @user.friends.paginate(:page => params[:page])
  end


  def news
    @user = current_user

    @feed_items = @user.microposts.class.new
    @user.friends.each do |friend|
      @feed_items += friend.news_feed
    end
    @feed_items = @feed_items.paginate(:page => params[:page])
  end

  def change_status
    @user = current_user
    @user_status = @user.user_status
    respond_to do |format|
      format.js
    end
  end

  def update_status
    current_user.status = params[:new_status]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                       :class => 'gravatar',
                       :gravatar => options)
  end
end

app/views/users/change_status.js.erb
$('#user_status').hide();
$('#user_status').replaceWith('<%= escape_javascript(render(:partial => 'shared/status_form')) %>');

app/views/users/friends.html.erb
<ul class="users">
<h3> <%= pluralize(@user.friends.count, "Friend") %> :</h3>

<% @user.friends.each do |friend| %>
    <li>
        <%= gravatar_for friend, :size => 30 %>

      <%= link_to friend.name, friend %>

            <%= link_to "Delete",
                        { :controller => "friendships", :action => "delete",
                          :id => friend.id },
                        :confirm =>
                                "Really delete friendship with #{friend.name}?" %>
        </li>
<% end %>
</ul>
<ul class="users">
<% unless @user.requested_friends.empty? %>
      <h3> <%= pluralize(@user.requested_friends.count, "Requested friend") %> :</h3>
    <% @user.requested_friends.each do |requester| %>
          <li>
          <%= gravatar_for requester, :size => 30 %>
          <%= link_to requester.name, requester %>

            <%= link_to "Accept",{
                        :controller => "friendships", :action => "accept",
                        :id => requester.id }%> /
            <%= link_to "Decline",
                        { :controller => "friendships", :action => "decline",
                          :id => requester.id },
                        :confirm =>
                                "Really decline friendship with #{requester.name}?" %>
          </li>
    <% end %>
<% end %>
</ul>
<ul class="users">
<% unless @user.pending_friends.empty? %>
      <h3> <%= pluralize(@user.pending_friends.count, "Pending friend") %> :</h3>
    <% @user.pending_friends.each do |pending_friend| %>
          <li>
          <%= gravatar_for pending_friend, :size => 30 %>
          <%= link_to pending_friend.name, pending_friend %>
          <%= link_to "Cancel request",
                          { :controller => "friendships", :action => "cancel",
                            :id => pending_friend.id },
                          :confirm =>
                                  "Cancel friendship request?" %>
          </li>
    <% end %>
<% end %>
</ul>

app/views/users/index.html.erb
<h2>All users</h2>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, :size => 30 %>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/news.erb
      <table class="front" summary="For signed-in users">
        <tr>
          <td class="main">
            <h1 class="micropost">Friends news</h1>
            <%= render 'shared/news_feed' %>
          </td>
        </tr>
      </table>

app/views/users/news.html.erb
      <table class="front" summary="For signed-in users">
        <tr>
          <td class="main">
            <h1 class="micropost">Friends news</h1>
            <%= render 'shared/news_feed' %>
          </td>
        </tr>
      </table>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="sidebar round">
        <ul class="users">
        <h1>
          <p align="center"><%= gravatar_for @user, :size => 170 %> </p> <br/>
          <p align="center"><%= link_to @user.name, @user %></p>
        </h1>
          <li><%= friendship_status(current_user, @user) %>
            <% unless Friendship.exists?(current_user, @user) || @user==current_user %>
                <br />
                <%= link_to "Request friendship with #{@user.name}", friendships_path(:id => @user.id ), :method => :post,
                            :confirm => "Send friend request to #{@user.name}?" %>
            <% end %>
        </ul>
      <ul class="users">
      <h2><li><%= link_to @friends_title, user_friends_path %></li></h2>
        <% for friend in @user.friends %>
            <li>
              <%= gravatar_for friend %>
              <%= link_to friend.name, friend %>
            </li>
        <% end %>
        <br/>
        <h2><li><%= link_to "Albums", user_albums_path(@user.id) %></li></h2>
      </ul>

    </td>
    <td class="main">
      <table class="front" summary="For signed-in users">
        <tr>
          <td class="main">
            <div id="add_new_micropost">
              <h1 class="micropost">
              <%= link_to "Add post", new_user_micropost_path(:user_id => @user.id),:remote => "true",
                                   :method => :get %>
              </h1><br />
            </div>
            <strong>Microposts</strong> <%= @user.microposts.count %><br />
            <div id="message_feed">
            <%= render 'shared/feed' %>
            </div>
          </td>
        </tr>
      </table>
  </tr>
</table>