config/routes.rb
Rails3DeviseRspecCucumber::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  resources :users, :only => [:show, :index] do
    resources :microposts, :only => [:create, :destroy, :new]
    resources :albums, :only => [:create, :destroy, :index, :show] do
      resources :photos, :only => [:create, :destroy]
    end
  end

  resources :photos, :only => [:create, :destroy]

  resources :microposts, :only => [:create, :destroy, :new]

  resources :friendships

  resources :albums, :only => [:create, :destroy, :index, :show] do
    resources :photos, :only => [:create, :destroy]
  end

  resources :videos, :only => [:create, :destroy, :index, :show]

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'

  match "/users/:id/friends" => "users#friends", :as => :user_friends
  match "/users/:id" => "users#show", :as => :user_profile

  match "/friends" => "users#friends", :as => :current_user_friends

  match "/news" => "users#news", :as => :news

  match '/home', :to => 'home#index'
  match '/', :to => 'home#index'
  match '/users', :to => 'users#index'

  match "/users/:user_id/albums" => "albums#index", :as => :user_albums

  match "/change_status" => "users#change_status", :as => :user_change_status

  match "/update_status" => "users#update_status", :as => :user_update_status


  match "friendships/:action/:id", :controller => 'friendships', :action => /[a-z_]+/i
end

app/views/shared/ _search_form .erb
<% form_tag({ :action => "search" }, :method => "get") do %>
    <fieldset>
      <legend>Search</legend>
      <div class="form_row">
        <label for="q">Search for:</label>
        <%= text_field_tag "q", params[:q] %>
        <input type="submit" value="Search" />
      </div>
    </fieldset>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
    <table class="microposts" summary="User microposts" >
      <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
    </table>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <% if feed_item.creator %>

    <%= link_to gravatar_for(feed_item.creator), feed_item.creator %>
  </td>
  <td class="micropost">
    <span class="user">

      <%= link_to feed_item.creator.name, feed_item.creator %>
      <% end %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user == feed_item.user || current_user == feed_item.creator%>
      <td>
        <%= link_to "delete", user_micropost_path(feed_item.user_id, feed_item.id), :method => :delete,
                    :confirm => "You sure?",
                    :title => feed_item.content %>

      </td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<h1 class="micropost">
  Add post
</h1><br />
<%= form_for @micropost do |f| %>
    <div class="field">
      <%= f.text_area :content %>
      <%=f.hidden_field :user_id, :value => @user.id%>
    </div>
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
<% end %>

app/views/shared/_news_feed.erb
<% unless @feed_items.empty? %>
    <%= will_paginate @feed_items %>
    <table class="microposts" summary="User microposts">
      <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
    </table>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_news_feed_item.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.creator), feed_item.creator %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to feed_item.creator.name, feed_item.creator %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
</tr>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <h2>Your Friends</h2>
    <ul>
      <% for friendship in @user.friendships %>
          <li>
            <%= h friendship.friend.name %>
            (<%= link_to "remove", friendship, :method => :delete %>)
          </li>
      <% end %>
    </ul>
  </table>
</div>

app/views/shared/_status_form.html.erb
<%= form_for (current_user, :url => user_update_status_path, :html => { :method => :put })  do |f| %>
    <div class="field">
      <%= f.text_field :new_status %>
      <%=f.hidden_field :user_id, :value => @user.id%>
    </div>
    <div class="actions">
      <%= f.submit "Update" %>
    </div>
<% end %>