config/routes.rb
Rails3DeviseRspecCucumber::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  resources :users, :only => [:show, :index] do
    resources :microposts, :only => [:create, :destroy, :new]
    resources :albums, :only => [:create, :destroy, :index, :show] do
      resources :photos, :only => [:create, :destroy]
    end
  end

  resources :photos, :only => [:create, :destroy]

  resources :microposts, :only => [:create, :destroy, :new]

  resources :friendships

  resources :albums, :only => [:create, :destroy, :index, :show] do
    resources :photos, :only => [:create, :destroy]
  end

  resources :videos, :only => [:create, :destroy, :index, :show]

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'

  match "/users/:id/friends" => "users#friends", :as => :user_friends
  match "/users/:id" => "users#show", :as => :user_profile

  match "/friends" => "users#friends", :as => :current_user_friends

  match "/news" => "users#news", :as => :news

  match '/home', :to => 'home#index'
  match '/', :to => 'home#index'
  match '/users', :to => 'users#index'

  match "/users/:user_id/albums" => "albums#index", :as => :user_albums

  match "/change_status" => "users#change_status", :as => :user_change_status

  match "/update_status" => "users#update_status", :as => :user_update_status


  match "friendships/:action/:id", :controller => 'friendships', :action => /[a-z_]+/i
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :user_id

  belongs_to :user

  has_many :photos

  #def photos
  #  Photo.where("album_id = ?", id)
  #end
end

app/controllers/albums_controller.rb
class  AlbumsController < ApplicationController
  def create
    user = current_user
    @album  = user.albums.build(params[:album])
    if @album.save
      flash[:success] = "Album created!"
      redirect_to  :back
    else
      flash[:success] = "Error: album don't created"
      render  :back
    end
  end

  def index
    @user = current_user unless @user = User.find_by_id(params[:user_id])
    @album = Album.new
    @albums = @user.albums
  end

  def show
    @user = current_user unless @user = User.find_by_id(params[:user_id])
    @album  = @user.albums.find_by_id(params[:id])
    @photos = @album.photos
    @photo = Photo.new
  end

  def destroy
    user = User.find_by_id(params[:user_id])
    album  = user.albums.find_by_id(params[:id])
    album.destroy
    redirect_to :back
  end

end

app/views/albums/index.html.erb
<h2>Photo Albums: </h2>

<% unless @albums.empty? %>
    <table class="microposts" summary="User microposts">
    <% for album in @albums %>
          <tr>
            <td>
              <%= link_to album.name, user_album_path(@user.id, album.id) %>
            </td>
            <td>
              <% if current_user == @user %>
                  <%= link_to "delete", user_album_path(@user.id, album.id), :method => :delete, :confirm => "You sure?"%>
              <% end %>
            </td>
            <td>
              <%= album.created_at %>
            </td>
        </tr>
    <% end %>
    </table>
<% end %>

<% if current_user == @user %>
    <%= form_for @album do |f| %>
        <div >
          <%= f.text_field:name %>
          <%=f.hidden_field :user_id, :value => current_user.id%>
          <%= f.submit "Create Album" %>
        </div>
    <% end %>
<% end %>

app/views/albums/show.html.erb
<% unless @photos.empty? %>
    <div id="photos">
      <% @album.photos.each do |photo| %>
          <div class="photo">
            <%=link_to image_tag(photo.image_url(:album_preview).to_s),photo.image_url %>
            <div class="name"><p align="center"><%= photo.name %></p></div>
            <% if current_user == @user %>
            <div class="actions">
              <p align="center"><%= link_to "remove", user_album_photo_path(@user.id, @album.id, photo.id), :confirm => 'Are you sure?', :method => :delete %></p>
            </div>
            <% end %>
          </div>
      <% end %>
      <div class="clear"></div>
    </div>
<% end %>

<% if current_user == @user %>
    <%= form_for @photo do |f| %>
        <%= f.hidden_field :album_id, :value => @album.id %>
        <%= f.hidden_field :user_id, :value => @user.id %>
        <p>
          <%= f.label :name %><br />
          <%= f.text_field :name %>
        </p>
        <p>
          <%= f.file_field :image %>
        </p>
        <p><%= f.submit %></p>
    <% end %>
<% end %>