config/routes.rb
Rails3DeviseRspecCucumber::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  resources :users, :only => [:show, :index] do
    resources :microposts, :only => [:create, :destroy, :new]
    resources :albums, :only => [:create, :destroy, :index, :show] do
      resources :photos, :only => [:create, :destroy]
    end
  end

  resources :photos, :only => [:create, :destroy]

  resources :microposts, :only => [:create, :destroy, :new]

  resources :friendships

  resources :albums, :only => [:create, :destroy, :index, :show] do
    resources :photos, :only => [:create, :destroy]
  end

  resources :videos, :only => [:create, :destroy, :index, :show]

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'

  match "/users/:id/friends" => "users#friends", :as => :user_friends
  match "/users/:id" => "users#show", :as => :user_profile

  match "/friends" => "users#friends", :as => :current_user_friends

  match "/news" => "users#news", :as => :news

  match '/home', :to => 'home#index'
  match '/', :to => 'home#index'
  match '/users', :to => 'users#index'

  match "/users/:user_id/albums" => "albums#index", :as => :user_albums

  match "/change_status" => "users#change_status", :as => :user_change_status

  match "/update_status" => "users#update_status", :as => :user_update_status


  match "friendships/:action/:id", :controller => 'friendships', :action => /[a-z_]+/i
end

app/views/layouts/_footer.html.erb
<nav class="round">
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
  </ul>
</nav>

app/views/layouts/_menu.erb
<nav class="round + menu">
  <ul>
    <li>
      <%= link_to "Profile", current_user%>
    </li>
    <li>
      <%= link_to "Friends", current_user_friends_path, :class => 'brand' %>
    </li>
    <li>
      <%= link_to "News", news_path %>
    </li>
    <li>
      <%= link_to "Users", users_path %>
    </li>
    <li>
      <%= link_to "Albums", albums_path %>
    </li>
  </ul>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="round + navigation">
  <ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
     <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
  </ul>
</nav>

<nav class="round + navigation">
  <% if user_signed_in? %>
Hello <%= link_to current_user.name, current_user %> !
  <% end %>
</nav>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--<%= stylesheet_link_tag "application", :media => "all" %>-->
<%= stylesheet_link_tag "blueprint/screen", :media => 'screen' %>
<%= stylesheet_link_tag "blueprint/print",  :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= javascript_include_tag "application" %>

app/views/layouts/application.html.erb
<!doctype html>
<%= javascript_include_tag :defaults%>

<html>
  <head>
    <title>Ruby Social Network | <%= @title %></title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/stylesheets' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>
  <body>
    <div id="container" class="container">
      <header>
        <%= image_tag("logo.png", :alt => "Sample App", :class => "round") %>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <%= render 'layouts/menu' %>
      <section class="round">
        <%= yield %>
      </section>
      <footer>
        <%=  render 'layouts/footer' %>
      </footer>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>